import fs from 'fs'
import os from 'os'
import path from 'path'

/**
 * adminWorkspace — 佈署 `~/.teamuq` 管理工作區（plan_v1 §12 U6 / Part B）。
 *
 * app 啟動（whenReady、reconcile 之後）呼叫 `ensureAdminWorkspace()`：
 *   - 寫 `~/.teamuq/scripts/*.mjs`（查任務 / 查打卡 / 通用唯讀查詢 / 備份 DB）。
 *   - 寫 `~/.teamuq/CLAUDE.md`（目錄說明 + DB schema 摘要 + scripts 用法 + 安全須知）。
 *
 * **managed 檔案策略**：每個 managed 檔頭標記 MANAGED_MARKER；每次啟動「覆寫」這些
 * managed 檔（檔頭仍是該標記者才覆寫；使用者改過頭的檔不動，避免覆掉手改）。目錄裡
 * 使用者自加的其他檔一律不動。
 *
 * ⚠️ ABI 陷阱：scripts 為獨立 `.mjs`，**絕不可** require app 的 better-sqlite3
 * （Electron ABI ≠ 系統 Node ABI）。一律用 `node:sqlite`（Node 22+ 內建）。
 * 因此這些 scripts 用「系統 node」直接跑：`node ~/.teamuq/scripts/tasks.mjs`。
 */

/** managed 檔案標記（檔頭首行）。檔頭是此標記者，啟動時才覆寫。 */
const MANAGED_MARKER = 'auto-generated by teamuq-electron, do not edit'
const MANAGED_MARKER_JS = `// ${MANAGED_MARKER}`
const MANAGED_MARKER_MD = `<!-- ${MANAGED_MARKER} -->`

/** ~/.teamuq 解析：與 repo / migrate / secretStore 同一慣例（TEAMUQ_HOME 可覆寫測試）。 */
function teamuqDir(): string {
  const home = process.env['TEAMUQ_HOME'] || os.homedir()
  return path.join(home, '.teamuq')
}

// ---------------------------------------------------------------------------
// 各 script 內容（純字串；獨立 .mjs，node:sqlite，唯讀為主）
// ---------------------------------------------------------------------------

/** scripts 共用前綴：開 DB（唯讀）+ teamuq.db 路徑解析。 */
const SCRIPT_DB_HELPER = `import { DatabaseSync } from 'node:sqlite'
import os from 'node:os'
import path from 'node:path'

// teamuq.db 路徑：TEAMUQ_DB 覆寫 > TEAMUQ_HOME/.teamuq > ~/.teamuq
function dbPath() {
  if (process.env.TEAMUQ_DB) return process.env.TEAMUQ_DB
  const home = process.env.TEAMUQ_HOME || os.homedir()
  return path.join(home, '.teamuq', 'teamuq.db')
}

export function openDb(readOnly = true) {
  return new DatabaseSync(dbPath(), { readOnly })
}

export { dbPath }
`

const SCRIPT_QUERY = `${MANAGED_MARKER_JS}
// query.mjs — 通用唯讀查詢。用法：node query.mjs "SELECT ... "
// 安全：只允許 SELECT / PRAGMA / EXPLAIN / WITH 開頭，其餘（INSERT/UPDATE/DELETE/DROP…）一律拒絕。
import { openDb } from './_db.mjs'

const sql = (process.argv[2] || '').trim()
if (!sql) {
  console.error('用法：node query.mjs "SELECT ... "（唯讀，只接受 SELECT / WITH / PRAGMA / EXPLAIN）')
  process.exit(1)
}
const head = sql.replace(/^\\(+/, '').trimStart().slice(0, 8).toLowerCase()
if (!/^(select|with|pragma|explain)/.test(head)) {
  console.error('✗ 拒絕：只允許唯讀查詢（SELECT / WITH / PRAGMA / EXPLAIN）。任何寫入請先跑 backup-db.mjs 並改用 app。')
  process.exit(2)
}

const db = openDb(true)
try {
  const rows = db.prepare(sql).all()
  console.log(JSON.stringify(rows, null, 2))
  console.error(\`(\${rows.length} 列)\`)
} catch (e) {
  console.error('✗ 查詢失敗：', e.message)
  process.exit(1)
} finally {
  db.close()
}
`

const SCRIPT_TASKS = `${MANAGED_MARKER_JS}
// tasks.mjs — 列本地任務。用法：node tasks.mjs [關鍵字]
import { openDb } from './_db.mjs'

const kw = (process.argv[2] || '').trim()
const db = openDb(true)
try {
  const base = \`
    SELECT t.local_id, t.name, t.status, t.priority,
           t.created_at, t.updated_at, m.name AS milestone
    FROM tasks t
    LEFT JOIN milestones m ON m.local_id = t.milestone_local_id
    WHERE 1=1\`
  const rows = kw
    ? db.prepare(base + ' AND t.name LIKE ? ORDER BY t.updated_at DESC').all('%' + kw + '%')
    : db.prepare(base + ' ORDER BY t.updated_at DESC').all()

  if (rows.length === 0) { console.log('（無任務）'); process.exit(0) }
  for (const r of rows) {
    console.log(\`- \${r.name}  (\${r.status || '—'}/\${r.priority || '—'})  milestone=\${r.milestone || '—'}  updated=\${r.updated_at || '—'}\`)
  }
  console.error(\`(共 \${rows.length} 個任務)\`)
} finally {
  db.close()
}
`

const SCRIPT_PUNCHES = `${MANAGED_MARKER_JS}
// punches.mjs — 列打卡（近 N 天，含工時小計）。用法：node punches.mjs [天數=7]
import { openDb } from './_db.mjs'

const days = Math.max(1, parseInt(process.argv[2] || '7', 10) || 7)
const sinceIso = new Date(Date.now() - days * 86400000).toISOString()

const db = openDb(true)
try {
  const rows = db.prepare(\`
    SELECT punch_uid, session_id, task_id, type, name,
           started_at, ended_at, hours, status, ok, error, source_file, source_pos
    FROM punches
    WHERE created_at >= ?
    ORDER BY created_at DESC\`).all(sinceIso)

  if (rows.length === 0) { console.log(\`（近 \${days} 天無打卡）\`); process.exit(0) }
  let total = 0
  for (const r of rows) {
    const h = typeof r.hours === 'number' ? r.hours : 0
    total += h
    const okMark = r.ok === 1 ? '✓' : r.ok === 0 ? '✗' : '·'
    const src = r.source_file ? \`  src=\${r.source_file}:\${r.source_pos ?? '?'}\` : ''
    console.log(\`\${okMark} [\${r.type || '—'}] \${r.name || r.punch_uid}  \${h.toFixed(2)}h  \${r.started_at || ''}~\${r.ended_at || ''}  \${r.status || ''}\${r.error ? ' ERR:' + r.error : ''}\${src}\`)
  }
  console.error(\`(共 \${rows.length} 筆，工時小計 \${total.toFixed(2)} 小時 / 近 \${days} 天)\`)
} finally {
  db.close()
}
`

const SCRIPT_BACKUP = `${MANAGED_MARKER_JS}
// backup-db.mjs — wal_checkpoint(TRUNCATE) 後複製 teamuq.db 到 backups/（帶日期）。
// 用法：node backup-db.mjs    （任何寫入操作前都先跑這支留底）
import { DatabaseSync } from 'node:sqlite'
import os from 'node:os'
import path from 'node:path'
import fs from 'node:fs'

function teamuqDir() {
  if (process.env.TEAMUQ_DB) return path.dirname(process.env.TEAMUQ_DB)
  const home = process.env.TEAMUQ_HOME || os.homedir()
  return path.join(home, '.teamuq')
}

const dir = teamuqDir()
const src = process.env.TEAMUQ_DB || path.join(dir, 'teamuq.db')
if (!fs.existsSync(src)) {
  console.error('✗ 找不到 teamuq.db：' + src)
  process.exit(1)
}

// 先 checkpoint：把 WAL 收進主檔，複製單檔即完整快照（§2.11）。
const db = new DatabaseSync(src)
try {
  db.exec('PRAGMA wal_checkpoint(TRUNCATE)')
} catch (e) {
  console.error('（checkpoint 警告，續備份）：', e.message)
} finally {
  db.close()
}

const backupsDir = path.join(dir, 'backups')
fs.mkdirSync(backupsDir, { recursive: true })
const d = new Date()
const p2 = (n) => String(n).padStart(2, '0')
const stamp = \`\${d.getFullYear()}\${p2(d.getMonth() + 1)}\${p2(d.getDate())}-\${p2(d.getHours())}\${p2(d.getMinutes())}\${p2(d.getSeconds())}\`
const dest = path.join(backupsDir, \`teamuq-\${stamp}.db\`)
fs.copyFileSync(src, dest)
console.log('✓ 已備份：' + dest)
`

// ---------------------------------------------------------------------------
// CLAUDE.md（操作手冊）
// ---------------------------------------------------------------------------

const CLAUDE_MD = `${MANAGED_MARKER_MD}
# TeamUQ 本地資料工作區

這是 **TeamUQ 桌面 app** 的本地資料目錄。這個工作區只描述本機 SQLite 資料與輔助查詢腳本。

## 目錄內容

| 路徑 | 說明 |
|---|---|
| \`teamuq.db\` | **單一本地資料庫**（SQLite/WAL）。本工作區操作對象。 |
| \`teamuq.db-wal\` / \`teamuq.db-shm\` | WAL 日誌與共享記憶體（勿手動刪）。 |
| \`conversations.db\` | （退役中）舊對話 cache；事實來源是 JSONL，可重建。 |
| \`scripts/\` | 本手冊隨附的唯讀 / 備份 scripts（見下）。 |
| \`llm-sessions/\` | claude CLI 服務 session 專用 cwd。 |
| \`backups/\` | \`backup-db.mjs\` 產出的 teamuq.db 快照。 |
| \`*.migrated.<日期>\` | 一次性整併後的舊檔備份（**別刪**，保留 30 天供回溯）。 |

## scripts 用法

⚠️ 一律用**系統 node**（v22+，內建 \`node:sqlite\`）跑，**不要**用 app 的 better-sqlite3
（Electron ABI 不相容）。也**不要**在這裡 \`npm install\` / \`npm rebuild\`。

\`\`\`bash
# 通用唯讀查詢（只接受 SELECT / WITH / PRAGMA / EXPLAIN）
node ~/.teamuq/scripts/query.mjs "SELECT name, status FROM tasks LIMIT 20"

# 列本地任務；可加關鍵字過濾
node ~/.teamuq/scripts/tasks.mjs
node ~/.teamuq/scripts/tasks.mjs 報表

# 列打卡（近 N 天，預設 7，含工時小計）
node ~/.teamuq/scripts/punches.mjs 14

# 備份 DB（任何寫入前先跑；wal_checkpoint 後複製到 backups/）
node ~/.teamuq/scripts/backup-db.mjs
\`\`\`

> node 可能印出 \`ExperimentalWarning: SQLite ...\` 到 stderr，屬正常，可加
> \`--disable-warning=ExperimentalWarning\` 抑制：\`node --disable-warning=ExperimentalWarning ~/.teamuq/scripts/tasks.mjs\`

## DB schema 摘要

主鍵一律 \`local_id\`；跨表外鍵一律 \`*_local_id\`。資料以本地 SQLite 為準。

**實體 5 表**
- \`projects\` — 專案。關鍵：local_id / name / description。
- \`milestones\` — 里程碑，FK \`project_local_id\`。
- \`tasks\` — 任務，FK \`milestone_local_id\` / \`project_local_id\`。關鍵：status / priority / description。
- \`project_folders\` — 專案與資料夾多對多關聯。
- \`subtasks\` — 子任務（打卡產出），FK \`task_local_id\`。關鍵：is_settled / duration。

**帳本 2 表**
- \`punches\` — 打卡帳本（id 自增）。關鍵：punch_uid（冪等鍵）/ session_id / type / hours / status / ok / source_file+source_pos（JSONL 溯源）。唯一索引 (session_id, punch_uid)。
- \`notifications\` — 通知 / 補卡提示。關鍵：type / severity / ref_punch_uid / active / resolved_at。

**綁定 2 表**
- \`milestone_bindings\` — 里程碑↔專案資料夾綁定，PK \`milestone_local_id\`。關鍵：project_path / tool / custom_command。
- \`session_bindings\` — 任務↔CLI session 綁定，PK (task_local_id, session_id)。關鍵：is_active（每 task 至多一筆）/ monitoring（啟動自動恢復監測）。

**設定 / meta 2 表**
- \`app_settings\` — key-value JSON 設定。
- \`schema_meta\` — 遷移旗標 / parser 版本（與 user_version 正交）。

**crash-recovery 2 表**
- \`scan_watermarks\` — 掃描水位，PK session_id。關鍵：jsonl_file / consumed_pos（斷點續掃補卡）。
- \`punch_artifacts\` — 每次 Edit/Write 的 hunk 級行數，PK (punch_session_id, punch_uid, tool_use_id, hunk_index)。關鍵：file_path / lines_added / lines_removed / old_start。

**對話 cache 3 表**（可重建，事實來源是 JSONL）
- \`conv_state\` — 每檔已讀位移 / 下一 seq。PK file。
- \`conv_segments\` — 對話分段索引。PK (file, seg_no)。
- \`conv_messages\` — （v6 後退役，可能不存在）舊版逐則訊息 cache。

## 安全須知（務必遵守）

1. **任何寫入前先跑 \`backup-db.mjs\`**：scripts 預設唯讀（query.mjs 拒非 SELECT）；
   若要由 app 或你手動改資料，先 \`node ~/.teamuq/scripts/backup-db.mjs\` 留底。
2. **\`*.migrated.*\` 別刪**：那是一次性整併後的舊檔備份，保留供回溯。
3. **不要在這裡 \`npm install\` / \`npm rebuild\`**：本目錄不是 Node 專案；scripts 只靠系統 node 內建
   \`node:sqlite\`。安裝套件或 rebuild 不會有效果、還可能污染環境。
4. **WAL 檔別手刪**：\`teamuq.db-wal\` / \`-shm\` 是 SQLite 正常運作檔；要乾淨單檔請用 backup-db.mjs（內含 checkpoint）。
`

// ---------------------------------------------------------------------------
// managed 檔案寫入（每次啟動覆寫 managed 檔；非 managed / 手改檔不動）
// ---------------------------------------------------------------------------

interface ManagedFile {
  /** 相對 ~/.teamuq 的路徑。 */
  rel: string
  content: string
  /** 用於判斷既有檔是否仍為 managed（檔頭含此標記）。 */
  marker: string
}

const MANAGED_FILES: ManagedFile[] = [
  { rel: 'scripts/_db.mjs', content: `${MANAGED_MARKER_JS}\n${SCRIPT_DB_HELPER}`, marker: MANAGED_MARKER },
  { rel: 'scripts/query.mjs', content: SCRIPT_QUERY, marker: MANAGED_MARKER },
  { rel: 'scripts/tasks.mjs', content: SCRIPT_TASKS, marker: MANAGED_MARKER },
  { rel: 'scripts/punches.mjs', content: SCRIPT_PUNCHES, marker: MANAGED_MARKER },
  { rel: 'scripts/backup-db.mjs', content: SCRIPT_BACKUP, marker: MANAGED_MARKER },
  { rel: 'CLAUDE.md', content: CLAUDE_MD, marker: MANAGED_MARKER },
]

const STALE_MANAGED_FILES = ['scripts/platforms.mjs']

/**
 * 寫一個 managed 檔：
 *   - 不存在 → 寫。
 *   - 存在且檔頭含 marker（仍是 managed）→ 內容不同才覆寫（冪等省 I/O）。
 *   - 存在但檔頭無 marker（使用者改成自己的）→ **不動**（保護手改）。
 */
function writeManaged(baseDir: string, f: ManagedFile): 'written' | 'unchanged' | 'skipped-user' {
  const abs = path.join(baseDir, f.rel)
  fs.mkdirSync(path.dirname(abs), { recursive: true })

  if (fs.existsSync(abs)) {
    let existing = ''
    try {
      existing = fs.readFileSync(abs, 'utf8')
    } catch {
      existing = ''
    }
    // 檔頭（前 200 字內）不含 marker → 使用者接管，跳過。
    if (!existing.slice(0, 200).includes(f.marker)) return 'skipped-user'
    if (existing === f.content) return 'unchanged'
  }

  fs.writeFileSync(abs, f.content, 'utf8')
  return 'written'
}

function removeStaleManaged(baseDir: string, rel: string): 'removed' | 'absent' | 'skipped-user' {
  const abs = path.join(baseDir, rel)
  if (!fs.existsSync(abs)) return 'absent'
  let existing = ''
  try {
    existing = fs.readFileSync(abs, 'utf8')
  } catch {
    return 'skipped-user'
  }
  if (!existing.slice(0, 200).includes(MANAGED_MARKER)) return 'skipped-user'
  fs.rmSync(abs, { force: true })
  return 'removed'
}

export interface AdminWorkspaceReport {
  ok: boolean
  dir: string
  written: string[]
  unchanged: string[]
  removed: string[]
  skippedUser: string[]
  error?: string
}

/**
 * 佈署 / 對齊 `~/.teamuq` 管理工作區的 managed 檔（scripts + CLAUDE.md）。
 * 冪等、容錯：任何 I/O 失敗只回報、不丟例外（啟動不可被此卡死）。
 */
export function ensureAdminWorkspace(): AdminWorkspaceReport {
  const dir = teamuqDir()
  const report: AdminWorkspaceReport = {
    ok: true,
    dir,
    written: [],
    unchanged: [],
    removed: [],
    skippedUser: [],
  }
  try {
    fs.mkdirSync(dir, { recursive: true })
    for (const f of MANAGED_FILES) {
      const outcome = writeManaged(dir, f)
      if (outcome === 'written') report.written.push(f.rel)
      else if (outcome === 'unchanged') report.unchanged.push(f.rel)
      else report.skippedUser.push(f.rel)
    }
    for (const rel of STALE_MANAGED_FILES) {
      const outcome = removeStaleManaged(dir, rel)
      if (outcome === 'removed') report.removed.push(rel)
      else if (outcome === 'skipped-user') report.skippedUser.push(rel)
    }
  } catch (e) {
    report.ok = false
    report.error = e instanceof Error ? e.message : String(e)
  }
  return report
}

/**
 * 管理 session 的固定 cwd（= ~/.teamuq）。renderer 經 IPC 取得後，以此為 projectPath
 * 開固定的「管理 session」（taskId 依 scope 取自 ADMIN_SESSION_TASK_IDS）。
 */
export function adminWorkspacePath(): string {
  return teamuqDir()
}

/**
 * 管理 session scope（plan §12 U6 rev15，用戶拍板 2026-06-05）：
 * **平台設定與專案管理各自一個固定 session**（cwd 同為 ~/.teamuq，但 taskId 不同）→
 * 各自的 task_sessions 綁定持久、各自重開 resume 自己的對話。
 */
export type AdminScope = 'platform' | 'project'

/**
 * 兩個固定管理 session 的 taskId（各 scope 一個；固定字串不與真實任務 id 衝突，
 * 故各自的 session 綁定跨重開可 resume 自己的對話）。
 */
export const ADMIN_SESSION_TASK_IDS: Record<AdminScope, string> = {
  platform: '__teamuq-admin-platform__',
  project: '__teamuq-admin-project__',
}

/** 各 scope 管理 session 的 tab 顯示名（區分兩頁的固定對話）。 */
export const ADMIN_SESSION_LABELS: Record<AdminScope, string> = {
  platform: '管理：平台設定',
  project: '管理：專案',
}

/** 把任意輸入窄化為合法 AdminScope（非法 / 缺省 → 'platform'，與既有單一入口最相近）。 */
export function toAdminScope(value: unknown): AdminScope {
  return value === 'project' ? 'project' : 'platform'
}
